version: '3'

services:

  fuseki:
    container_name: fuseki
    ## Example:
    ## command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    image: secoresearch/fuseki:4.3.2
    ports:
      - "3030:3030"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./fuseki-configuration:/fuseki-base/configuration
      - ./fuseki-data:/fuseki-base/databases
      - ./wikidata:/wikidata:ro
      - ./jena-tools:/jena-tools:ro
    environment:
      ADMIN_PASSWORD: mySuperSecurePassword
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      ENABLE_UPLOAD: "true"
      QUERY_TIMEOUT: 10000 # in ms
